const express = require('express');
const path = require('path');
require('dotenv').config("./.env");
const bodyParser = require('body-parser');
const { Configuration, OpenAIApi } = require("openai");

const app = express();
const PORT = process.env.PORT || 4000;
var question = "";
var main_ans = "";

app.use(express.static("public"));
app.use(bodyParser.urlencoded({extended: true}));
app.use((req, res, next) => {
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.setHeader('Pragma', 'no-cache');
  res.setHeader('Expires', '0');
  next();
});


app.set('view engine', 'ejs');

// app.get('', function(req, res) {
//   res.sendFile(`${publicPath}/index.html`);
// });

app.get("", (req, res) => {
  question="";
  main_ans="";
  res.render('converter', {answer: [""], question: question});
});

app.post("/result", async (req, res) => {
  var question = req.body.question.trim();
  console.log(question);

  if(question) { // Only execute if question is not empty
    if(main_ans === "") { // Only call API if we don't already have an answer
      const configuration = new Configuration({
        apiKey: process.env.SECRET_KEY,
      });

      const openai = new OpenAIApi(configuration);

      var prompts = [
        "Q: It is important to understand that a well written piece has both 'complexity' and 'variations of sentences.' Humans tend to write with greater variances in sentences with some sentences being longer adjacent to shorter sentences and with greater complexity. AI sentences tend to be more uniform and basic. I will be asking you to create writing pieces for me, but I need it to have a good amount of complexity and variations as if it were written by a human. Do you understand? \nA: Yes, I understand. As an AI language model, I can generate text that mimics the natural variations and complexity found in human writing. I can adjust the length of sentences and the complexity of the vocabulary used in order to create a piece of writing that feels natural and engaging to the reader. Please let me know what topic you would like me to write about, and I will do my best to produce a piece of writing that meets your specifications.",
        "Q: Using the concepts shared previously, rewrite the following with a high degree of complexity and variations of sentences as if it were written by a human. Also, make it suitable for academic writings. \nA: Certainly! Here is my attempt at rewriting the given text with a high degree of complexity and sentence variation: It is of utmost importance to comprehend that a piece of writing that is deemed well-crafted must exhibit both intricacy and diversity in its sentence structure. Human writers tend to utilize a wider range of sentence lengths and structures, varying between elongated and brief sentences, and incorporating greater levels of intricacy. Conversely, the sentences generated by artificial intelligence models are often more homogeneous and simplistic in their construction. Therefore, it is incumbent upon me, as a language model, to strive towards creating writing pieces that are comparable to those produced by humans, featuring a multitude of sentence structures and a high degree of intricacy. I shall endeavor to fulfill this task by randomly generating complex and varied sentences, ensuring that the resultant pieces of writing are commensurate with the high standards that humans expect of their own writing.",
      ];
      

      var prompt = prompts.join("\n") + "Q: " + question + "\nA: ";

      try {
        const completion = await openai.createCompletion({
            "model": "text-davinci-003",
            "prompt": prompt,
            "max_tokens": 2500,
            "temperature": 1,
            "top_p": 1,
            "n": 1,
            "stream": false,
            "logprobs": null,
            "stop": ""
        });
        console.log(completion.data.choices[0].text);
        main_ans = completion.data.choices[0].text;

        var paragraphs = main_ans.split("\n");
        console.log(paragraphs);

        res.render("converter", { answer: paragraphs, question: question });
      } catch (err) {
        console.error(err);
        res.render("error");
      }
    } else {
      var paragraphs = main_ans.split("\n");
      console.log(paragraphs);
      res.render('converter', {answer: paragraphs, question: question});
    }
  } 
  else {
    question="";
    main_ans="";
    res.render('converter', {answer: [""], question: question}); // Empty answer
  }
});

// app.post("", async (req, res) => {
//   var question = req.body.question;
//   console.log(question);

//   if(question === "" || main_ans === "") {
//     const configuration = new Configuration({
//       apiKey: process.env.SECRET_KEY,
//     });
    
//     const openai = new OpenAIApi(configuration);
    
//     var prompts = [
//       "Q: It is important to understand that a well written piece has both 'complexity' and 'variations of sentences.' Humans tend to write with greater variances in sentences with some sentences being longer adjacent to shorter sentences and with greater complexity. AI sentences tend to be more uniform and basic. I will be asking you to create writing pieces for me, but I need it to have a good amount of complexity and variations as if it were written by a human. Do you understand? \nA: Yes, I understand. As an AI language model, I can generate text that mimics the natural variations and complexity found in human writing. I can adjust the length of sentences and the complexity of the vocabulary used in order to create a piece of writing that feels natural and engaging to the reader. Please let me know what topic you would like me to write about, and I will do my best to produce a piece of writing that meets your specifications.",
//       "Q: Using the concepts shared previously, rewrite the following with a high degree of complexity and variations of sentences as if it were written by a human. Also, make it suitable for academic writings. \nA: Certainly! Here is my attempt at rewriting the given text with a high degree of complexity and sentence variation: It is of utmost importance to comprehend that a piece of writing that is deemed well-crafted must exhibit both intricacy and diversity in its sentence structure. Human writers tend to utilize a wider range of sentence lengths and structures, varying between elongated and brief sentences, and incorporating greater levels of intricacy. Conversely, the sentences generated by artificial intelligence models are often more homogeneous and simplistic in their construction. Therefore, it is incumbent upon me, as a language model, to strive towards creating writing pieces that are comparable to those produced by humans, featuring a multitude of sentence structures and a high degree of intricacy. I shall endeavor to fulfill this task by randomly generating complex and varied sentences, ensuring that the resultant pieces of writing are commensurate with the high standards that humans expect of their own writing.",
//     ];
    
//     var prompt = prompts.join("\n") + "Q: " + question + "\nA: ";
  
//     try {
//       const completion = await openai.createCompletion({
//           "model": "text-davinci-003",
//           "prompt": prompt,
//           "max_tokens": 2500,
//           "temperature": 1,
//           "top_p": 1,
//           "n": 1,
//           "stream": false,
//           "logprobs": null,
//           "stop": ""
//       });
//       console.log(completion.data.choices[0].text);
//       main_ans = completion.data.choices[0].text;
    
//       var paragraphs = main_ans.split("\n");
//       console.log(paragraphs);
    
//       res.render("converter", { answer: paragraphs });
//     } catch (err) {
//       console.error(err);
//       res.render("error");
//     }
//   } else {
//     res.render('converter', {answer: question});
//   }
// });

app.get("*", (req, res) => {
  res.render("404");
});

app.listen(PORT, function() {
  console.log('Server running on port ' + PORT);
});